#ifndef DOMLETTE_NODETYPE_H
#define DOMLETTE_NODETYPE_H

#ifdef __cplusplus
extern "C" {
#endif

enum NodeType {
  ELEMENT_NODE=1,
  ATTRIBUTE_NODE,
  TEXT_NODE,
  CDATA_SECTION_NODE,
  ENTITY_REFERENCE_NODE,
  ENTITY_NODE,
  PROCESSING_INSTRUCTION_NODE,
  COMMENT_NODE,
  DOCUMENT_NODE,
  DOCUMENT_TYPE_NODE,
  DOCUMENT_FRAGMENT_NODE,
  NOTATION_NODE,
  XPATH_NAMESPACE_NODE, /* DOM Level 3 XPath (needed for compares) */
 };

#ifdef __cplusplus
}
#endif

#endif /* DOMLETTE_NODETYPE_H */
