<?xml version='1.0'?>
<fragment>
  <token>DOUBLE_DOT</token>
  <token>DOUBLE_COLON</token>
  <token>AT</token>
  <token>LEFT_PAREN</token>
  <token>LEFT_SQUARE</token>
  <token>COMMA</token>
  <token>LITERAL</token>
  <token>NLITERAL</token>
  <token>VARIABLE_REFERENCE</token>
  <token>WILDCARD_NAME</token>
  <token>MULTIPLY_OPERATOR</token>
  <token>FUNCTION_NAME</token>
  <token>DOUBLE_SLASH</token>
  <token>NOT_EQUAL</token>
  <token>LESS_THAN</token>
  <token>GREATER_THAN</token>
  <token>LESS_THAN_EQUAL</token>
  <token>GREATER_THAN_EQUAL</token>
  <token>OR</token>
  <token>AND</token>
  <token>DIV</token>
  <token>MOD</token>
  <token>COMMENT</token>
  <token>TEXT</token>
  <token>PROCESSING_INSTRUCTION</token>
  <token>NODE</token>
  <token>ANCESTOR</token>
  <token>ANCESTOR_OR_SELF</token>
  <token>ATTRIBUTE</token>
  <token>CHILD</token>
  <token>DESCENDANT</token>
  <token>DESCENDANT_OR_SELF</token>
  <token>FOLLOWING</token>
  <token>FOLLOWING_SIBLING</token>
  <token>NAMESPACE</token>
  <token>PARENT</token>
  <token>PRECEDING</token>
  <token>PRECEDING_SIBLING</token>
  <token>SELF</token>
  <token>NODE_TYPE</token>
  <token>AXIS_NAME</token>
  <token>RELATIONAL_OP</token>
  <token>EQUALITY_OP</token>
</fragment>
